apiVersion: v1
data:
  clusterissuer: "false"
  domain: 35.203.123.59.nip.io
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
